language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  # php-cs-fixer is nice to have but HHVM and nightly
  # don't support it, so make sure to remove it for CI
  - composer remove --dev friendsofphp/php-cs-fixer

script:
  - php ./vendor/bin/phpunit -d error_reporting=-1 tests
