language: php

stage: tests

php:
  - 7.4
  - nightly
  - 7.3
  - 7.2

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - rm composer.lock
  - composer remove --dev friendsofphp/php-cs-fixer vimeo/psalm twig/twig kint-php/kint
  - composer require twig/twig:$TWIG kint-php/kint:$KINT

script:
  - php ./vendor/bin/phpunit -d error_reporting=-1 tests

stages:
  - analysis
  - tests

env:
  - TWIG=^2 KINT=^3
  - TWIG=^3 KINT=^3
  - TWIG=^3 KINT=dev-master

jobs:
  allow_failures:
    - php: nightly

  include:
    - php: 7.0
      install:
        - composer remove --dev phpunit/phpunit friendsofphp/php-cs-fixer vimeo/psalm twig/twig kint-php/kint
        - composer require twig/twig:2.4 kint-php/kint:^3
        - composer update
        - composer require --dev phpunit/phpunit ^5
      env: TWIG=2.4 KINT=^3

    - php: 7.1
      install:
        - composer remove --dev phpunit/phpunit friendsofphp/php-cs-fixer vimeo/psalm twig/twig
        - composer require twig/twig:^2
        - composer update
        - composer require --dev phpunit/phpunit ^5
      env: TWIG=^2

    # Check if `composer format` was run correctly
    - stage: analysis
      install: composer install
      script:
        - composer format
        - git status
        - git diff-files --quiet --exit-code
      env: analysis_type="composer format" TWIG=^3

    # Check if code passes phpstan/psalm static analysis
    - stage: analysis
      install: composer install
      script: composer analyze
      env: analysis_type="composer analyze" TWIG=^3

    # Preliminary test run
    - stage: analysis
      install: composer install
      env: TWIG=^3
