language: php

stage: tests

php:
  - 7.2
  - nightly
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - rm composer.lock
  - composer remove --dev friendsofphp/php-cs-fixer vimeo/psalm

script:
  - php ./vendor/bin/phpunit -d error_reporting=-1 tests

stages:
  - analysis
  - tests

jobs:
  include:
    # 5.3 on precise
    - php: 5.3
      dist: precise

    # Test twig 1
    - after_install:
        - composer remove twig/twig
        - composer require twig/twig:^1
      env: TWIG=1
    - php: 5.3
      dist: precise
      after_install:
        - composer remove twig/twig
        - composer require twig/twig:^1.34
      env: TWIG=1

    # Check if `composer format` was run correctly
    - stage: analysis
      install: composer install
      script: composer format && git status && git diff-files --quiet --exit-code
      env: analysis_type="composer format"

    # Check if code passes phpstan/psalm static analysis
    - stage: analysis
      install: composer install
      script: composer analyze
      env: analysis_type="composer analyze"

    # Preliminary test run
    - stage: analysis
      install: composer install
